export const DrinkData = [
  {
    _id: 0,
    name: "Silent Pool Gin",
    price: 20,
    image: "/assets/images/silentPool.png",
    image_1: "/assets/images/whiteSilent.png",
    image_2: "/assets/images/indieProducts/silentPoolGin1.png",
    image_3: "/assets/images/indieProducts/silent2.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    strength: 3,
    type: "cocktail",
    spiritType: "gin",
  },
  {
    _id: 1,
    name: "Monkey 47 Gin",
    price: 17,
    image: "/assets/images/monkey47.png",
    image_1: "/assets/images/whiteMonkey.png",
    image_2: "/assets/images/indieProducts/monkey1.png",
    image_3: "/assets/images/indieProducts/monkey2.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    strength: 3,
    type: "cocktail",
    spiritType: "gin",
  },
  {
    _id: 2,
    name: "Bellewood Parms",
    price: 15,
    image: "/assets/images/belleWood.png",
    image_1: "/assets/images/indieProducts/belleWood.png",
    image_2: "",
    image_3: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    strength: 3,
    type: "cocktail",
    spiritType: "gin",
  },
  {
    _id: 3,
    name: "Silent Pool Mini",
    price: 10,
    image: "/assets/images/miniPool.png",
    image_1: "/assets/images/miniPool.png",
    image_2: "/assets/images/indieProducts/silentPoolGin1.png",
    image_3: "/assets/images/indieProducts/silent2.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    strength: 3,
    type: "cocktail",
    spiritType: "gin",
  },
  {
    _id: 4,
    name: "McHenry Butterfly Gin",
    price: 50,
    image: "/assets/images/mcHenry.png",
    image_1: "/assets/images/indieProducts/mcHenry.png",
    image_2: "",
    image_3: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborums",
    strength: 2,
    type: "cocktail",
    spiritType: "gin",
  },
  // {
  //   "_id": 5,
  //   "name": "Alkemist Gin",
  //   "price": "$30",
  //   "image": "",
  //   "image_1": "",
  //   "image_2": "",
  //   "image_3": "",
  //   "description": "tastes good with grapes and shit",
  //   "strength": 3,
  //   "type" : "cocktail",
  //   "spiritType": "gin"
  // },
  // {
  //   "_id": 6,
  //   "name": "Pandan Syrup",
  //   "price": "$20",
  //   "image": "",
  //   "image_1": "",
  //   "image_2": "",
  //   "image_3": "",
  //   "description": "the pandan syrup is good with a lot of thing but expires quickly",
  //   "strength": 0,
  //   "type" : "non-alcoholic",
  //   "spiritType": "none"
  // },
  // {
  //   "_id": 7,
  //   "name": "Chrysanthemum Gin cocktail",
  //   "price": "$20",
  //   "image": "",
  //   "image_1": "",
  //   "image_2": "",
  //   "image_3": "",
  //   "description": "the OG cocktail I made which I still don't know if it's good or not",
  //   "strength": 3,
  //   "type" : "cocktail",
  //   "spiritType": "gin"
  // },
  // {
  //   "_id": 8,
  //   "name": "Milk clarified whisky sour",
  //   "price": "$20",
  //   "image": "",
  //   "image_1": "",
  //   "image_2": "",
  //   "image_3": "",
  //   "description": "some experimental shit",
  //   "strength": 3,
  //   "type" : "cocktail",
  //   "spiritType": "whisky"
  // },
  // {
  //   "_id": 9,
  //   "name": "Fat washed bacon whisky",
  //   "price": "$20",
  //   "image": "",
  //   "image_1": "",
  //   "image_2": "",
  //   "image_3": "",
  //   "description": "more experiemental shit",
  //   "strength": 4,
  //   "type" : "cocktail",
  //   "spiritType": "whisky"
  // },
  // {
  //   "_id": 10,
  //   "name": "cinnamon whisky",
  //   "price": "$20",
  //   "image": "",
  //   "image_1": "",
  //   "image_2": "",
  //   "image_3": "",
  //   "description": "this was good at the bar last time",
  //   "strength": 4,
  //   "type" : "cocktail",
  //   "spiritType": "whisky"
  // }
];
